linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  godot:
    exclude:
      - ^\s*.+:.+$
      - ^\s*(?:=+|/+|-+|\++)
  unparam:
    check-exported: true

issues:
  exclude-rules:
    # prevent lexerr on type assertions with field access
    - linters:
        - errorlint
      source: \w\.\(\*?\w+\)\.\w+
    - path: (?:_test|test_util)\.go$
      linters:
        - errcheck
        - errorlint
        - gosec
