version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    godot:
      exclude:
        - ^\s*\p{Ll}           # Exclude lowercase comments
        - ^\s*(?:=+|/+|-+|\++) # Exclude lines that are not identifiers
        - ^\s*\w+$             # Exclude single-word identifiers
        - ^(\s*\p{Lu}+)+$      # Exclude sectioning comments (all uppercase)
        - '[\w\d]:\s+'         # Exclude colons
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
