version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    godot:
      exclude:
        - ^\s*.+:.+$
        - ^\s*(?:=+|/+|-+|\++)
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errorlint
        source: \w\.\(\*?\w+\)\.\w+
      - linters:
          - errcheck
          - errorlint
          - gosec
        path: (?:_test|test_util)\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
