name: Lint

on: [pull_request]

jobs:
  review:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Lint Project
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
